name: CI Practice

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Step
        run: echo "Building application..."

      - name: Show Node Version
        run: node --version

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test Step
        run: echo "Running tests..."

      - name: Test Success
        run: echo "All tests passed!"
